apiVersion: v1
kind: Service
metadata:
  name: mob-nsapp-service
  labels:
    app: mob-nsapp
spec:
  type: NodePort
  selector:
    app: mob-nsapp
  ports:
    - protocol: TCP
      port: 1234
      nodePort: 30002
      targetPort: 80
