apiVersion: v1
kind: Service
metadata:
  name: mob-nsapp-service
  labels:
    app: mob-nsapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.certificateArn }}
spec:
  type: LoadBalancer
  selector:
    app: mob-nsapp
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
