apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::473293451041:server-certificate/mob-nsapp-certificate
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  selector:
    app: hello-world
